env:
  name: PushBlockCollab
  version: 0.1.0
  path: envs/PushBlockCollab/build.x86_64
setting:
  width: 80
  height: 80
  time_scale: 10
param:
  n_episode: 100
  max_time_step: 100
  learning_rate: 0.001
  gamma: 0.95
  epsilon: 0.8
  batch_size: 20
log:
  path:
